#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
  ssh:
    install-server: true
    allow-pw: false

  identity:
    hostname: ubuntu-template
    username: ${ssh_username}
    password: "${user_password_hash}"

  user-data:
    users:
      - default
      - name: ansible
        system: true
        groups: [sudo]
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        ssh_authorized_keys:
          - ${ansible_ssh_key}
      - name: ${ssh_username}
        ssh_authorized_keys:
          - ${personal_ssh_key}

  storage:
    layout:
      name: lvm